Define modals in prototype (Quick setup)
Qvant-lab/qui pull request #11
Opened 2020-12-09 15:42 UTC by Tim152

2020-12-09 15:56 UTC, ViZhe requested changes

2020-12-09 15:56 UTC, ViZhe commented on README.md
> +  <q-input v-model="value" />
судя по конфигу выше тут должно быть `yo-input`, чтобы оно заработало

2020-12-09 15:56 UTC, ViZhe commented on src/qComponents/index.js
> +  }
возможно стоит консольнуть предупреждение, если это не применилось и NODE_ENV не продакшен, чтоб исключить неожиданности

2020-12-09 15:56 UTC, ViZhe commented on src/qComponents/index.js
> +      prefix && isString(prefix) ? name.replace('Q', prefix) : name;
с регулярочкой как-то понадёжнее, если вдруг первой будет не Q по каким то причинам
`name.replace(/^Q/, prefix)`

2020-12-09 16:23 UTC, ViZhe commented on README.md
> +this.$dialog({ ... }) // calls QDialog
тут мы как бы находимся в main.js, а там нет this, так что этот пример скорее путает,

2020-12-10 09:54 UTC, ViZhe approved these changes

2020-12-10 09:56 UTC, Esvalirion approved these changes

2020-12-10 09:56 UTC, merged