[QTable] change api
Qvant-lab/qui pull request #30
Opened 2020-12-29 14:51 UTC by Tim152

- add groups
- add settings for groups
- update stories

2020-12-29 15:13 UTC, ViZhe requested changes

2020-12-29 15:13 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +            <template v-for="(group, groupIndex) in groupsOfColumns">
colgroup?

2020-12-29 15:17 UTC, Esvalirion commented on src/qComponents/QTable/src/QTable.vue
> +        borderColor: group.color ?? 'transparent'
лучше вообще не добавлять стиль, он есть днфолтный в цсс

2020-12-30 14:48 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +                    :rowKey="rowData.key"
row-key?

2020-12-30 15:09 UTC, ViZhe approved these changes

2021-01-11 08:45 UTC, merged