[QTable] Remove thead if there are no values in columns
Qvant-lab/qui pull request #37
Opened 2021-01-15 16:18 UTC by Esvalirion

2021-01-15 16:19 UTC, shamilfrontend approved these changes

2021-01-18 08:58 UTC, ViZhe requested changes

2021-01-18 08:58 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +          return value || slots?.header;
сокращенные записи + value нужно проверять на существование, приведение к типу тут съест 0

2021-01-19 08:22 UTC, ViZhe approved these changes

2021-01-19 09:25 UTC, ViZhe approved these changes

2021-01-19 12:17 UTC, Tim152 approved these changes

2021-01-19 12:18 UTC, merged