[QMessageBox] Add prop width
Qvant-lab/qui pull request #39
Opened 2021-01-19 08:02 UTC by shamilfrontend

Added props width  for Message container, value can be string or number

2021-01-19 08:10 UTC, Esvalirion approved these changes

2021-01-19 13:17 UTC, ViZhe approved these changes

2021-01-20 09:01 UTC, Tim152 requested changes

2021-01-20 09:01 UTC, Tim152 commented on src/qComponents/QMessageBox/src/QMessageBox.vue
> +      :class="rootClasses"
wrapClass чтобы консистентно было с QScrollbar

2021-01-20 09:09 UTC, shamilfrontend commented on src/qComponents/QMessageBox/src/QMessageBox.vue
> +      :class="rootClasses"
fix

2021-01-20 10:01 UTC, Tim152 approved these changes

2021-01-20 10:01 UTC, merged