[QTag] Update docs, add tests, fix button
Qvant-lab/qui pull request #46
Opened 2021-01-21 09:58 UTC by ViZhe

2021-01-21 12:14 UTC, shamilfrontend commented on src/qComponents/QTag/src/QTag.vue
>        class="q-tag__close q-icon-close"
`type="button"`

2021-01-21 13:40 UTC, ViZhe commented on src/qComponents/QTag/src/QTag.vue
>        class="q-tag__close q-icon-close"
добавил

2021-01-22 07:57 UTC, Tim152 requested changes

2021-01-22 07:57 UTC, Tim152 commented on src/qComponents/QTag/src/QTag.vue
> +     * whether close button shown
whether is close button shown

2021-01-22 08:38 UTC, Tim152 approved these changes

2021-01-22 08:38 UTC, Esvalirion approved these changes

2021-01-22 08:43 UTC, merged