[QInputNumber] fix null value, fix "-" value, add placeholder
Qvant-lab/qui pull request #50
Opened 2021-01-27 06:59 UTC by Esvalirion

2021-01-27 10:42 UTC, ViZhe requested changes

2021-01-27 10:42 UTC, ViZhe commented on src/qComponents/QInputNumber/QInputNumber.test.js
> +  it('should match snapshot', async () => {
async лишний

2021-01-27 10:42 UTC, ViZhe commented on src/qComponents/QInputNumber/QInputNumber.test.js
> +import Component from './src/QInputNumber.vue';
.vue лишнее

2021-01-28 07:42 UTC, ViZhe requested changes

2021-01-28 07:42 UTC, ViZhe commented on src/qComponents/QInputNumber/src/QInputNumber.vue
> +      if (value && value !== null) {
второе условие всегда истина

2021-01-28 08:46 UTC, ViZhe approved these changes

2021-01-29 08:27 UTC, Tim152 approved these changes

2021-01-29 14:42 UTC, merged