Localization
Qvant-lab/qui pull request #6
Opened 2020-12-04 13:45 UTC by Tim152

- add localization
- add new import api
- fix bug with addEventListener helper

2020-12-05 10:32 UTC, shamilfrontend commented on stories/components/QTabPane.stories.js
> +import QTabs from '../../src/qComponents/QTabs';
поменять местами импорты :-) `QTabs` главнее

2020-12-05 10:38 UTC, shamilfrontend commented on src/qComponents/index.js
> +  Vue.prototype._i18n = i18n;
мб проверку на всякий случай?

```
if (!Vue.prototype._i18n) {
  Vue.prototype._i18n = i18n;
}
```

2020-12-05 10:45 UTC, shamilfrontend commented on src/qComponents/QSelect/src/QSelect.vue
> +      if (this.loading) return loadingText;
```
if (this.loading) return this.loadingText ?? this.$t('QSelect.loading');;
```
const loadingText наверное лишняя будет

2020-12-07 08:49 UTC, ViZhe requested changes

2020-12-07 08:49 UTC, ViZhe commented on src/qComponents/constants/localizationConfig.js
> +  ru: {
удобнее было бы разбить локали на файлы, так их проще дифать, да и если ещё локали добавятся то этот файл разрастется

2020-12-07 08:49 UTC, ViZhe commented on src/qComponents/index.js
> +const kebabCase = require('lodash/kebabCase');
import { merge, kebabCase } from 'lodash-es';

2020-12-07 08:49 UTC, ViZhe commented on src/qComponents/index.js
> +  'QMessageBox'
алфавитный порядок предпочтительней

2020-12-08 15:47 UTC, Tim152 commented on src/qComponents/QSelect/src/QSelect.vue
> +      if (this.loading) return loadingText;
норм, для читабельности

2020-12-08 16:38 UTC, ViZhe commented on package.json
> +  "readme": "ERROR: No README data found!",
выглядит неожиданно

2020-12-08 16:48 UTC, ViZhe commented on src/qComponents/constants/locales/index.js
> +  if (isI18nExist) return;
возможно стоит консольнуть предупреждение о том, что интернационализация не применена

2020-12-09 07:59 UTC, ViZhe approved these changes

2020-12-09 08:02 UTC, merged