[QTable] Rebuild sticky columns, update selectable prop
Qvant-lab/qui pull request #62
Opened 2021-02-12 10:14 UTC by Esvalirion

2021-02-12 11:50 UTC, shamilfrontend commented on src/qComponents/QTable/src/QTable.vue
> +      const table = this.$refs.QTable;
`const { QTable } = this.$refs;`

2021-02-12 13:31 UTC, ViZhe requested changes

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +    isSelectColSticked() {
isSelectableColumnSticked

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +      return this.isSelectable && this.selectableColumn.sticky;
return this.isSelectable && this.selectableColumn?.sticky ?? false;

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +            triggerRight: totalWidth + 64,
magic number

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +            conditionOut = triggerRight + offset * 2 < scroll + rootWidth;
`triggerRight + offset * 2 `
похоже на какую-то переменную осмысленную

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +          const conditionChanges =
`canObserversChange` или что-то в таком духе, сейчас не понятно о чем переменная

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +          let conditionOut = triggerLeft >= scroll;
conditionIn conditionOut неоднозначно обозначают о чем переменная

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +      /* eslint-disable no-param-reassign */
лучше отключать в конкретных местах, чтобы не пропустить неожиданное переназначение и чтобы оно не отключилось для всего файла если вдруг не включить эту проверку после

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +      return this.stickedOffsets[position]?.[key];
лучше возвращать умышленно null если ожидается что там может быть undefined, либо пустую строку как выше, в зависимости от ожидания того когда что использует этот метод

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/QTable.vue
> +        totalLeftWidth += 64;
magic number

2021-02-12 13:31 UTC, ViZhe commented on src/qComponents/QTable/src/components/QTableRow/index.vue
> +      observer-key="QTable-checkboxes"
q-table-checkboxes и в других подобных местах

2021-02-15 10:58 UTC, ViZhe approved these changes

2021-02-15 11:20 UTC, shamilfrontend approved these changes

2021-03-01 06:12 UTC, Tim152 requested changes

2021-03-01 06:12 UTC, Tim152 commented on src/qComponents/QTable/src/QTable.vue
> +    this.$watch(
почему в императивном?

2021-03-15 10:50 UTC, Esvalirion commented on src/qComponents/QTable/src/QTable.vue
> +    this.$watch(
вью не следит за домом

2021-03-15 11:41 UTC, Tim152 approved these changes

2021-03-15 11:53 UTC, merged