[QRangeSelector] add range selector
Qvant-lab/qui pull request #80
Opened 2021-07-09 14:56 UTC by Esvalirion

2021-07-16 09:36 UTC, ViZhe requested changes

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      firstValue: null,
наверное это ближе к начальное значение и конечное, чем к первое и второе

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      let p = 0;
раскрыть бы понятнее

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +        e *= 10;
магик нумбер

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +        : [];
лучше ифачнут и инвертнуть условие чем такой тернарник

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    },
выглядит как драй

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +          : (100 * (value - this.min)) / (this.max - this.min);
плохо читается присвоение

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      };
тоже очень похоже на драй

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    this.getValues();
уже есть immediate

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +        this.firstValue = Array.isArray(this.value)
а если значение меньше чем мин в этом случае?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      this.firstValue = Math.max(this.min, this.value);
что будет при this.value === null?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    getValues() {
так же значение может быть не числовой строкой что приведёт к нан

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    onPathClick(event) {
handle

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +        : newValue.toFixed(this.precision);
плохо читается присвоение

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +              return Math.abs(b - newValue) < Math.abs(a - newValue) ? b : a;
`a` вроде как undefined при первом проходе?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      let isFirstButtonChanged = true;
что подразумевается под изменением первой кнопки?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      } = this.$refs.path.getBoundingClientRect();
достаточно `return this.$refs.path.getBoundingClientRect();`

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    getStopStyle(position) {
не понятно что такое stop style

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      if (tabIndex === 0) {
ты сам это передаёшь в компонент, соответственно ты можешь на этом уровне разделить логику без ифака

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    changeButtonPosition({ newValue, tabIndex }) {
это обработчик - handle

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    changeButtonPosition({ newValue, tabIndex }) {
+ тот же поинт по поводу tabIndex

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +    class="q-range-selector__button-wrapper focus-visible"
focus-visible?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +  <div
а че это не button?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +    @mousedown.stop="handleButtonDrag"
stop порождает неожиданные конфликты логик, точно без него не обойтись?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +    onArrowDown({ key }) {
handle

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +    @keydown.up.prevent="onArrowDown"
это умышленно всё onArrowDown?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +        : newPosition;
плохо читается

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +      if (targetValue < min) {
чем отличается реализация на ифаках от Math.max/min выше?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +      document.removeEventListener('mouseup', this.handleButtonMovingEnd);
возможно стоит пробовать отписываться на дестрое тоже?

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/q-range-selector.scss
> +  &.is-vertical {
модификатор

2021-07-16 09:36 UTC, ViZhe commented on src/qComponents/QRangeSelector/src/q-range-selector.scss
> +    // }
?

2021-07-16 09:42 UTC, shamilfrontend commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      @click="onPathClick"
handle)

2021-07-16 09:43 UTC, shamilfrontend commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +          v-for="(item, key) in steps"
item -> step

2021-07-16 09:43 UTC, shamilfrontend commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +          v-for="(item, key) in captionsList"
item -> caption

2021-07-19 09:27 UTC, Esvalirion commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      this.firstValue = Math.max(this.min, this.value);
очвеидно this.min

2021-07-19 09:30 UTC, Esvalirion commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +    getValues() {
написал валидатор

2021-07-19 09:37 UTC, Esvalirion commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +              return Math.abs(b - newValue) < Math.abs(a - newValue) ? b : a;
я не задал начальное значение, значит оно автоматом взялось из первого элемента массива

2021-07-19 09:44 UTC, Esvalirion commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +      let isFirstButtonChanged = true;
Был ли клик ближе к первой кнопке, чем ко второй

2021-07-19 09:47 UTC, Esvalirion commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +    class="q-range-selector__button-wrapper focus-visible"
![image](https://user-images.githubusercontent.com/1199337/126140830-3565bfcc-8109-4e0c-8e0f-206b6dc682aa.png)

2021-07-19 13:03 UTC, ViZhe requested changes

2021-09-15 13:13 UTC, shamilfrontend commented on src/qComponents/QRangeSelector/src/QRangeSelector.vue
> +  name: 'QRangeSelector',
done

2021-09-15 13:13 UTC, shamilfrontend commented on src/qComponents/QRangeSelector/src/components/RangeSelectorButton/index.vue
> +      if (targetValue < min) {
код изменился)

2021-09-16 08:07 UTC, ViZhe requested changes

2021-09-16 08:07 UTC, ViZhe commented on src/qComponents/QSlider/src/q-slider.scss
> +.slider-button {
разнеси блоки на отдельные файлы

2021-09-16 08:07 UTC, ViZhe commented on src/vars.scss
> +  --box-shadow-line: inset 1px 1px 2px rgba(var(--color-rgb-blue), 0.2),
если это используется только в слайдере то думаю нет смысла выносить это в общие vars

2021-09-16 12:35 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/SliderCaptions/index.vue
> +  <div class="slider-captions">
ок

2021-09-20 08:57 UTC, ViZhe requested changes

2021-09-20 08:57 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderButton/index.vue
> +      window.addEventListener('mousemove', this.handleDragging);
document?

2021-09-20 08:57 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderButton/index.vue
> +      window.removeEventListener('contextmenu', this.handleDragEnd);
кажется так что стоит отписываться при дестрое компонента, на случай если он заанмаунтится без наступления маусап

2021-09-20 08:57 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderSteps/index.vue
> +      v-for="(item, key) in stepsList"
step

2021-09-20 08:57 UTC, ViZhe commented on src/qComponents/QSlider/src/components/QSliderSteps/index.vue
> +      class="q-slider-steps__item"
step

2021-09-20 08:57 UTC, ViZhe commented on src/qComponents/QSlider/src/q-slider.scss
> +@import './styles/q-slider-captions';
.scss

2021-09-20 08:57 UTC, ViZhe commented on stories/components/QSlider/Breakpoints.js
> +      show-steps
используй дефолты, чтобы это можно было переопределять
во всех примерах

2021-09-20 11:29 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/QSliderSteps/index.vue
> +      v-for="(item, key) in stepsList"
`stepItem` поставил, у меня step prop уже есть)

2021-09-20 12:00 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/QSliderButton/index.vue
> +      window.addEventListener('mousemove', this.handleDragging);
ок

2021-09-20 12:14 UTC, shamilfrontend commented on src/qComponents/QSlider/src/components/QSliderButton/index.vue
> +      window.removeEventListener('contextmenu', this.handleDragEnd);
добавить отписку при `beforeDestroy`

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/QSlider.vue
> +        :vertical="vertical"
isVertical?

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/QSlider.vue
> +        :range="range"
isRanged

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/QSlider.vue
> +        this.$emit('input', [this.minValue, this.maxValue]);
второй аругмент в переменную и понадобится лишь один вызов

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/QSlider.vue
> +      if (this.range) {
if (!this.range) return;
this.$emit('input', [this.minValue, this.maxValue]);

--- 
везде

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/QSlider.vue
> +          this.$emit('input', [this.value[0], this.max]);
один эмит

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/components/QSliderBar/index.vue
> +    vertical: {
isVertical

2021-09-20 13:51 UTC, Tim152 commented on src/qComponents/QSlider/src/components/QSliderBar/index.vue
> +    range: {
isRanged

2021-09-20 15:00 UTC, shamilfrontend commented on src/qComponents/QSlider/src/QSlider.vue
> +          this.$emit('input', [this.value[0], this.max]);
done

2021-09-20 15:06 UTC, shamilfrontend commented on src/qComponents/QSlider/src/QSlider.vue
> +        this.$emit('input', [this.minValue, this.maxValue]);
done

2021-09-20 15:06 UTC, shamilfrontend commented on src/qComponents/QSlider/src/QSlider.vue
> +      if (this.range) {
done

2021-09-20 15:28 UTC, shamilfrontend commented on stories/components/QSlider/Breakpoints.js
> +      show-steps
поправил

2021-09-21 07:46 UTC, ViZhe approved these changes

2021-09-21 07:52 UTC, Tim152 approved these changes

2021-09-21 07:53 UTC, merged